# Generated by Django 5.1.7 on 2026-03-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_topicscenario"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_key", models.SlugField(max_length=80)),
                ("title", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["topic__domain", "sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[("quantum", "Quantum"), ("ai", "AI")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("topic_key", models.SlugField(max_length=80)),
                ("title", models.CharField(max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["domain"],
            },
        ),
        migrations.CreateModel(
            name="TechStackTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("ml", "ML"),
                            ("quantum", "Quantum"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("homepage_url", models.URLField(blank=True)),
                ("docs_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_key", models.SlugField(max_length=120, unique=True)),
                ("node_type", models.CharField(max_length=80)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("quantum", "Quantum"),
                            ("ai", "AI"),
                            ("shared", "Shared"),
                        ],
                        default="shared",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("canonical_url", models.URLField(blank=True)),
                ("is_live_entangled", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="portfolio.knowledgebranch",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="portfolio.knowledgetopic",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "topic__domain",
                    "branch__sort_order",
                    "sort_order",
                    "title",
                ],
            },
        ),
        migrations.AddField(
            model_name="knowledgebranch",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="portfolio.knowledgetopic",
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeNodeTechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_links",
                        to="portfolio.knowledgenode",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_links",
                        to="portfolio.techstacktool",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeNodeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("entangled", "Entangled"),
                            ("depends_on", "Depends On"),
                        ],
                        default="related",
                        max_length=20,
                    ),
                ),
                ("is_live", models.BooleanField(default=True)),
                ("weight", models.FloatField(default=1.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="portfolio.knowledgenode",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="portfolio.knowledgenode",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_node", "to_node", "link_type"),
                        name="uq_knowledge_node_link_pair_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeNodeResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("doc", "Documentation"),
                            ("paper", "Research Paper"),
                            ("repo", "GitHub Repository"),
                            ("resource", "Resource"),
                            ("course", "Course"),
                            ("video", "Video"),
                            ("blog", "Blog"),
                            ("cookbook", "Cookbook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("source", models.CharField(blank=True, max_length=120)),
                ("summary", models.TextField(blank=True)),
                ("external_id", models.CharField(blank=True, max_length=120)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="portfolio.knowledgenode",
                    ),
                ),
            ],
            options={
                "ordering": ["resource_type", "title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("node", "resource_type", "url"),
                        name="uq_knowledge_node_resource_url",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="knowledgebranch",
            constraint=models.UniqueConstraint(
                fields=("topic", "branch_key"), name="uq_knowledge_branch_topic_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgenodetechstack",
            constraint=models.UniqueConstraint(
                fields=("node", "tool"), name="uq_knowledge_node_tool"
            ),
        ),
    ]
